### ISSUE TITLE
Installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by BernhardEgger** [prakharbhardwaj1/Powerofsmile_FlappyBird-OpenCv#1]
Those are the steps I had to do differently to install it on Ubuntu 20.04

- pip3 and python3 instead of pip and python
- Somehow when installing the dependencies I had also to run `pip3 install cmake`
- change line 51 to shape_predictor= 'shape_predictor_68_face_landmarks.dat'

After this I receive the following error:
```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
fps: 30
Traceback (most recent call last):
  File "game.py", line 131, in <module>
    top.x, top.y = window_size[0], random.randint(120 - 1000, window_size[1] - 120 - space_between_pipes - 1000)
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (-880, -889, -9)

```

It looks like it can connect to the camera as I get 30 fps but also something goes wrong as the windowsize is derived from the camera?
I then tried to take the second camera as I have one attached to a notebook using ` VID_CAP = cv.VideoCapture(1)` - no idea if that is correct, but now a black screen opened and I get a sligthly different error (numbers changed and can't open camera by index):

```
can't open camera by index
fps: 0
Traceback (most recent call last):
  File "game.py", line 131, in <module>
    top.x, top.y = window_size[0], random.randint(120 - 1000, window_size[1] - 120 - space_between_pipes - 1000)
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (-880, -1369, -489)

```

any suggestions?

**Comment by BernhardEgger** [comment]
I also added the following debug prints 

```
print("w:", cv.CAP_PROP_FRAME_WIDTH)
print("h:", cv.CAP_PROP_FRAME_HEIGHT)
print("wsize:", window_size)
```

leading to the following output:
```
w: 3
h: 4
wsize: (640.0, 480.0)

```

it looks like some of the values in there are hardcoded and lead invalid ranges?

I get it running by dividing everything by 4 (assuming you ran it with a fullHD camera
`            top.x, top.y = window_size[0], random.randint(120//4 - 1000//4, window_size[1] - 120//4 - space_between_pipes//4 - 1000//4)`

This makes it running but the pipes are too big - I think it would make sense to adapt sizes of pipes etc. to the camera size??


I also get the following error when I want to restart with space (second time, not first time):
```
Traceback (most recent call last):
  File "game.py", line 109, in <module>
    pipe_frames.popleft()
IndexError: pop from an empty deque
```
